from app.models.entities import Agent, AuditLog, SecurityRule, Task, TaskStep, User, UserProfile, Workflow


def build_agents() -> list[Agent]:
    return [
        Agent(
            id="1",
            name="意图识别 Agent",
            description="分析用户输入，识别用户意图和需求",
            type="intent",
            status="running",
            enabled=True,
            tasks_completed=12580,
            tasks_total=12600,
            avg_response_time="45ms",
            tokens_used=850000,
            tokens_limit=1000000,
            success_rate=99.8,
            last_active="刚刚",
        ),
        Agent(
            id="2",
            name="安全检测 Agent",
            description="检测和过滤敏感内容，保障系统安全",
            type="security",
            status="running",
            enabled=True,
            tasks_completed=12578,
            tasks_total=12578,
            avg_response_time="12ms",
            tokens_used=120000,
            tokens_limit=500000,
            success_rate=100,
            last_active="刚刚",
        ),
        Agent(
            id="3",
            name="搜索 Agent",
            description="在知识库中搜索相关文档和信息",
            type="search",
            status="idle",
            enabled=True,
            tasks_completed=8920,
            tasks_total=8950,
            avg_response_time="320ms",
            tokens_used=450000,
            tokens_limit=800000,
            success_rate=99.6,
            last_active="2 分钟前",
        ),
        Agent(
            id="4",
            name="写作 Agent",
            description="生成高质量的文本内容和回复",
            type="write",
            status="waiting",
            enabled=True,
            tasks_completed=6540,
            tasks_total=6560,
            avg_response_time="1.2s",
            tokens_used=680000,
            tokens_limit=1000000,
            success_rate=99.7,
            last_active="1 分钟前",
        ),
        Agent(
            id="5",
            name="摘要 Agent",
            description="为长文本生成简洁的摘要",
            type="default",
            status="idle",
            enabled=True,
            tasks_completed=4320,
            tasks_total=4350,
            avg_response_time="800ms",
            tokens_used=320000,
            tokens_limit=600000,
            success_rate=99.3,
            last_active="5 分钟前",
        ),
        Agent(
            id="6",
            name="输出 Agent",
            description="格式化并发送最终响应",
            type="output",
            status="idle",
            enabled=True,
            tasks_completed=12000,
            tasks_total=12000,
            avg_response_time="25ms",
            tokens_used=95000,
            tokens_limit=200000,
            success_rate=100,
            last_active="刚刚",
        ),
    ]


def build_audit_logs() -> list[AuditLog]:
    return [
        AuditLog(
            id="1",
            timestamp="2026-04-01 10:32:15",
            action="敏感词检测",
            user="system",
            resource="消息过滤",
            status="warning",
            ip="192.168.1.***",
            details="检测到敏感内容，已自动过滤",
        ),
        AuditLog(
            id="2",
            timestamp="2026-04-01 10:30:45",
            action="用户登录",
            user="zhang***",
            resource="认证系统",
            status="success",
            ip="10.0.0.***",
            details="管理员登录成功",
        ),
        AuditLog(
            id="3",
            timestamp="2026-04-01 10:28:30",
            action="权限变更",
            user="admin",
            resource="用户管理",
            status="success",
            ip="10.0.0.***",
            details="修改用户 li*** 的角色为运维员",
        ),
        AuditLog(
            id="4",
            timestamp="2026-04-01 10:25:10",
            action="异常请求",
            user="anonymous",
            resource="API 网关",
            status="error",
            ip="203.0.113.***",
            details="检测到异常请求模式，已阻止",
        ),
        AuditLog(
            id="5",
            timestamp="2026-04-01 10:20:00",
            action="工作流修改",
            user="chen***",
            resource="工作流编辑器",
            status="success",
            ip="10.0.0.***",
            details="更新客户服务工作流配置",
        ),
        AuditLog(
            id="6",
            timestamp="2026-04-01 10:15:30",
            action="Token 超限",
            user="system",
            resource="写作Agent",
            status="warning",
            ip="-",
            details="Agent Token 使用量达到 90%",
        ),
    ]


def build_security_rules() -> list[SecurityRule]:
    return [
        SecurityRule(
            id="1",
            name="敏感词过滤",
            description="过滤包含敏感词汇的用户输入",
            type="filter",
            enabled=True,
            hit_count=1250,
            last_triggered="2 分钟前",
        ),
        SecurityRule(
            id="2",
            name="SQL 注入检测",
            description="检测并阻止 SQL 注入攻击",
            type="block",
            enabled=True,
            hit_count=89,
            last_triggered="1 小时前",
        ),
        SecurityRule(
            id="3",
            name="XSS 防护",
            description="过滤跨站脚本攻击代码",
            type="block",
            enabled=True,
            hit_count=156,
            last_triggered="30 分钟前",
        ),
        SecurityRule(
            id="4",
            name="频率限制",
            description="限制单用户请求频率",
            type="alert",
            enabled=True,
            hit_count=432,
            last_triggered="5 分钟前",
        ),
    ]


def build_tasks() -> list[Task]:
    return [
        Task(
            id="1",
            title="用户咨询 - 产品功能",
            description="用户询问产品的高级功能使用方法",
            status="completed",
            priority="medium",
            created_at="2026-04-01 10:30:00",
            completed_at="2026-04-01 10:30:45",
            agent="意图识别Agent",
            tokens=450,
            duration="45s",
            steps=[
                TaskStep(
                    id="1-1",
                    title="安全检测",
                    status="completed",
                    agent="安全检测Agent",
                    message="消息安全检测通过",
                    started_at="2026-04-01 10:30:00",
                    finished_at="2026-04-01 10:30:02",
                    tokens=45,
                ),
                TaskStep(
                    id="1-2",
                    title="意图识别",
                    status="completed",
                    agent="意图识别Agent",
                    message="识别到产品功能咨询意图",
                    started_at="2026-04-01 10:30:02",
                    finished_at="2026-04-01 10:30:08",
                    tokens=120,
                ),
                TaskStep(
                    id="1-3",
                    title="写作输出",
                    status="completed",
                    agent="写作Agent",
                    message="已生成最终回复",
                    started_at="2026-04-01 10:30:08",
                    finished_at="2026-04-01 10:30:45",
                    tokens=285,
                ),
            ],
        ),
        Task(
            id="2",
            title="文档搜索 - 技术规格",
            description="搜索产品技术规格相关文档",
            status="running",
            priority="high",
            created_at="2026-04-01 10:32:00",
            agent="搜索Agent",
            tokens=320,
            steps=[
                TaskStep(
                    id="2-1",
                    title="检索知识库",
                    status="running",
                    agent="搜索Agent",
                    message="正在搜索相关文档",
                    started_at="2026-04-01 10:32:00",
                    tokens=320,
                ),
            ],
        ),
        Task(
            id="3",
            title="内容生成 - 邮件回复",
            description="为客户生成专业的邮件回复",
            status="pending",
            priority="medium",
            created_at="2026-04-01 10:33:00",
            agent="写作Agent",
            tokens=0,
        ),
        Task(
            id="4",
            title="安全检测 - 敏感词过滤",
            description="检测用户输入中的敏感内容",
            status="completed",
            priority="high",
            created_at="2026-04-01 10:28:00",
            completed_at="2026-04-01 10:28:12",
            agent="安全检测Agent",
            tokens=85,
            duration="12s",
        ),
        Task(
            id="5",
            title="用户咨询 - 账单问题",
            description="用户咨询账单和付款相关问题",
            status="failed",
            priority="high",
            created_at="2026-04-01 10:25:00",
            agent="意图识别Agent",
            tokens=120,
            duration="--",
        ),
    ]


def build_users() -> list[User]:
    return [
        User(
            id="1",
            name="张管理",
            email="zhang***@company.com",
            role="admin",
            status="active",
            last_login="2026-04-01 10:30",
            total_interactions=1250,
            created_at="2023-06-01",
        ),
        User(
            id="2",
            name="李运维",
            email="li***@company.com",
            role="operator",
            status="active",
            last_login="2026-04-01 09:15",
            total_interactions=856,
            created_at="2023-08-15",
        ),
        User(
            id="3",
            name="王查看",
            email="wang***@company.com",
            role="viewer",
            status="active",
            last_login="2026-03-31 18:20",
            total_interactions=234,
            created_at="2023-10-20",
        ),
        User(
            id="4",
            name="刘测试",
            email="liu***@company.com",
            role="operator",
            status="inactive",
            last_login="2026-03-30 14:30",
            total_interactions=567,
            created_at="2023-09-05",
        ),
    ]


def build_user_profiles() -> dict[str, UserProfile]:
    return {
        "1": UserProfile(
            user_id="1",
            tags=["核心客户", "已开通高级版", "需要周报"],
            preferred_language="zh",
            source_channel="dingtalk",
            notes="偏好中文回复，关注安全与合规能力。",
            platform_accounts=[
                {"platform": "dingtalk", "account_id": "ding-zhang-admin"},
                {"platform": "telegram", "account_id": "tg_zhang_admin"},
            ],
            permissions=["dashboard:view", "users:manage", "workflows:edit"],
        ),
        "2": UserProfile(
            user_id="2",
            tags=["运维", "夜班支持"],
            preferred_language="zh",
            source_channel="wecom",
            notes="负责线上巡检与异常处理。",
            platform_accounts=[{"platform": "wecom", "account_id": "wecom-li-ops"}],
            permissions=["dashboard:view", "security:view"],
        ),
    }


def build_workflows() -> list[Workflow]:
    return [
        Workflow(
            id="wf-1",
            name="客户服务工作流",
            description="从消息触发到多 Agent 协作输出的默认流程",
            version="2.1",
            status="active",
            updated_at="2026-04-01 11:00:00",
            trigger="message.keyword",
            agent_bindings=["security", "intent", "search", "write", "output"],
            nodes=[
                {"id": "1", "type": "trigger", "position": {"x": 50, "y": 200}, "data": {"label": "消息触发"}},
                {"id": "2", "type": "agent", "position": {"x": 280, "y": 120}, "data": {"label": "安全检测", "agentType": "security", "status": "idle"}},
                {"id": "3", "type": "agent", "position": {"x": 280, "y": 280}, "data": {"label": "意图识别", "agentType": "intent", "status": "running", "tokens": 150}},
                {"id": "4", "type": "condition", "position": {"x": 520, "y": 200}, "data": {"label": "意图分支"}},
                {"id": "5", "type": "agent", "position": {"x": 760, "y": 120}, "data": {"label": "搜索 Agent", "agentType": "search", "status": "waiting"}},
                {"id": "6", "type": "agent", "position": {"x": 760, "y": 280}, "data": {"label": "写作 Agent", "agentType": "write", "status": "idle"}},
                {"id": "7", "type": "aggregate", "position": {"x": 1000, "y": 200}, "data": {"label": "聚合结果"}},
                {"id": "8", "type": "output", "position": {"x": 1240, "y": 200}, "data": {"label": "发送结果"}},
            ],
            edges=[
                {"id": "e1-2", "source": "1", "target": "2"},
                {"id": "e1-3", "source": "1", "target": "3"},
                {"id": "e2-4", "source": "2", "target": "4"},
                {"id": "e3-4", "source": "3", "target": "4"},
                {"id": "e4-5", "source": "4", "sourceHandle": "true", "target": "5"},
                {"id": "e4-6", "source": "4", "sourceHandle": "false", "target": "6"},
                {"id": "e5-7", "source": "5", "target": "7"},
                {"id": "e6-7", "source": "6", "target": "7"},
                {"id": "e7-8", "source": "7", "target": "8"},
            ],
        )
    ]
