from __future__ import annotations

from copy import deepcopy
from datetime import UTC, datetime


class InMemoryStore:
    def __init__(self) -> None:
        self.demo_user = {
            "id": "admin-1",
            "name": "管理员",
            "email": "admin@workbot.ai",
            "role": "admin",
        }
        self.system_settings = {
            "general": {
                "dashboard_auto_refresh": True,
                "show_system_status": True,
            },
            "agent_api": {
                "providers": {
                    provider_id: {
                        "enabled": False,
                        "base_url": "",
                        "model": "",
                        "organization_id": "",
                        "project_id": "",
                        "group_id": "",
                        "endpoint_path": "",
                        "notes": "",
                        "api_key": None,
                    }
                    for provider_id in (
                        "claude",
                        "codex",
                        "openai",
                        "kimi",
                        "minimax",
                        "gemini",
                        "deepseek",
                        "openapi",
                    )
                }
            },
        }

        self.dashboard_stats = [
            {
                "key": "active_agents",
                "title": "活跃 Agent",
                "value": 12,
                "description": "3 个运行中",
                "trend_value": 8,
                "trend_positive": True,
            },
            {
                "key": "workflows",
                "title": "工作流",
                "value": 24,
                "description": "本周新增 5 个",
                "trend_value": 12,
                "trend_positive": True,
            },
            {
                "key": "pending_tasks",
                "title": "待处理任务",
                "value": 156,
                "description": "较昨日减少 23 个",
                "trend_value": 15,
                "trend_positive": False,
            },
            {
                "key": "today_runs",
                "title": "今日执行",
                "value": "2.4k",
                "description": "平均响应 120ms",
                "trend_value": 5,
                "trend_positive": True,
            },
        ]

        self.chart_data = [
            {"time": "00:00", "requests": 120, "tokens": 4500},
            {"time": "04:00", "requests": 80, "tokens": 3200},
            {"time": "08:00", "requests": 450, "tokens": 18000},
            {"time": "12:00", "requests": 680, "tokens": 27200},
            {"time": "16:00", "requests": 590, "tokens": 23600},
            {"time": "20:00", "requests": 320, "tokens": 12800},
            {"time": "24:00", "requests": 180, "tokens": 7200},
        ]

        self.realtime_logs = [
            {
                "id": "rt-1",
                "timestamp": "10:32:15",
                "type": "success",
                "agent": "意图识别Agent",
                "message": "成功识别用户意图: 文档搜索",
            },
            {
                "id": "rt-2",
                "timestamp": "10:32:14",
                "type": "info",
                "agent": "搜索Agent",
                "message": "正在搜索相关文档...",
            },
            {
                "id": "rt-3",
                "timestamp": "10:32:12",
                "type": "success",
                "agent": "安全检测Agent",
                "message": "消息安全检测通过",
            },
            {
                "id": "rt-4",
                "timestamp": "10:32:10",
                "type": "info",
                "agent": "触发器",
                "message": "收到新消息，开始处理工作流",
            },
            {
                "id": "rt-5",
                "timestamp": "10:31:58",
                "type": "warning",
                "agent": "写作Agent",
                "message": "Token 使用量接近限制",
            },
        ]
        self.operational_logs = []

        self.agents = [
            {
                "id": "1",
                "name": "意图识别 Agent",
                "description": "分析用户输入，识别用户意图和需求",
                "type": "intent",
                "status": "running",
                "enabled": True,
                "tasks_completed": 12580,
                "tasks_total": 12600,
                "avg_response_time": "45ms",
                "tokens_used": 850000,
                "tokens_limit": 1000000,
                "success_rate": 99.8,
                "last_active": "刚刚",
            },
            {
                "id": "2",
                "name": "安全检测 Agent",
                "description": "检测和过滤敏感内容，保障系统安全",
                "type": "security",
                "status": "running",
                "enabled": True,
                "tasks_completed": 12578,
                "tasks_total": 12578,
                "avg_response_time": "12ms",
                "tokens_used": 120000,
                "tokens_limit": 500000,
                "success_rate": 100,
                "last_active": "刚刚",
            },
            {
                "id": "3",
                "name": "搜索 Agent",
                "description": "在知识库中搜索相关文档和信息",
                "type": "search",
                "status": "idle",
                "enabled": True,
                "tasks_completed": 8920,
                "tasks_total": 8950,
                "avg_response_time": "320ms",
                "tokens_used": 450000,
                "tokens_limit": 800000,
                "success_rate": 99.6,
                "last_active": "2 分钟前",
            },
            {
                "id": "4",
                "name": "写作 Agent",
                "description": "生成高质量的文本内容和回复",
                "type": "write",
                "status": "waiting",
                "enabled": True,
                "tasks_completed": 6540,
                "tasks_total": 6560,
                "avg_response_time": "1.2s",
                "tokens_used": 680000,
                "tokens_limit": 1000000,
                "success_rate": 99.7,
                "last_active": "1 分钟前",
            },
            {
                "id": "5",
                "name": "摘要 Agent",
                "description": "为长文本生成简洁的摘要",
                "type": "default",
                "status": "idle",
                "enabled": True,
                "tasks_completed": 4320,
                "tasks_total": 4350,
                "avg_response_time": "800ms",
                "tokens_used": 320000,
                "tokens_limit": 600000,
                "success_rate": 99.3,
                "last_active": "5 分钟前",
            },
            {
                "id": "6",
                "name": "输出 Agent",
                "description": "格式化并发送最终响应",
                "type": "output",
                "status": "idle",
                "enabled": True,
                "tasks_completed": 12000,
                "tasks_total": 12000,
                "avg_response_time": "25ms",
                "tokens_used": 95000,
                "tokens_limit": 200000,
                "success_rate": 100,
                "last_active": "刚刚",
            },
            {
                "id": "7",
                "name": "翻译 Agent",
                "description": "多语言翻译和本地化",
                "type": "default",
                "status": "error",
                "enabled": False,
                "tasks_completed": 1200,
                "tasks_total": 1250,
                "avg_response_time": "600ms",
                "tokens_used": 180000,
                "tokens_limit": 300000,
                "success_rate": 96,
                "last_active": "1 小时前",
            },
        ]

        self.tasks = [
            {
                "id": "1",
                "title": "用户咨询 - 产品功能",
                "description": "用户询问产品的高级功能使用方法",
                "status": "completed",
                "priority": "medium",
                "created_at": "2024-01-15 10:30:00",
                "completed_at": "2024-01-15 10:30:45",
                "agent": "意图识别Agent",
                "tokens": 450,
                "duration": "45s",
                "result": {
                    "kind": "draft_message",
                    "title": "功能答复草稿",
                    "summary": "已生成一版面向客户的产品功能说明草稿",
                    "content": "您好，\n\n关于您关心的高级功能，我们已经整理出一版简要说明，可直接用于客户答复或二次润色。\n\n1. 当前能力覆盖工作流编排、权限控制与协作可视化。\n2. 如需更详细的配置说明，可继续补充使用场景。\n\n此致\nWorkBot",
                    "bullets": [
                        "适合作为客户回访或产品说明的初版内容。",
                        "如需改成邮件、公告或 FAQ，可以继续复用当前任务上下文。",
                    ],
                    "references": [
                        {
                            "title": "产品功能清单",
                            "detail": "建议结合最新功能清单进一步补充细节",
                        }
                    ],
                },
            },
            {
                "id": "2",
                "title": "文档搜索 - 技术规格",
                "description": "搜索产品技术规格相关文档",
                "status": "running",
                "priority": "high",
                "created_at": "2024-01-15 10:32:00",
                "completed_at": None,
                "agent": "搜索Agent",
                "tokens": 320,
                "duration": None,
            },
            {
                "id": "3",
                "title": "内容生成 - 邮件回复",
                "description": "为客户生成专业的邮件回复",
                "status": "pending",
                "priority": "medium",
                "created_at": "2024-01-15 10:33:00",
                "completed_at": None,
                "agent": "写作Agent",
                "tokens": 0,
                "duration": None,
            },
            {
                "id": "4",
                "title": "安全检测 - 敏感词过滤",
                "description": "检测用户输入中的敏感内容",
                "status": "completed",
                "priority": "high",
                "created_at": "2024-01-15 10:28:00",
                "completed_at": "2024-01-15 10:28:12",
                "agent": "安全检测Agent",
                "tokens": 85,
                "duration": "12s",
            },
            {
                "id": "5",
                "title": "用户咨询 - 账单问题",
                "description": "用户咨询账单和付款相关问题",
                "status": "failed",
                "priority": "high",
                "created_at": "2024-01-15 10:25:00",
                "completed_at": None,
                "agent": "意图识别Agent",
                "tokens": 120,
                "duration": "--",
            },
            {
                "id": "6",
                "title": "数据分析 - 用户行为",
                "description": "分析用户最近的行为模式",
                "status": "cancelled",
                "priority": "low",
                "created_at": "2024-01-15 10:20:00",
                "completed_at": None,
                "agent": "分析Agent",
                "tokens": 0,
                "duration": None,
            },
        ]

        self.task_steps = {
            "1": [
                {
                    "id": "1-1",
                    "title": "接收用户消息",
                    "status": "completed",
                    "agent": "触发器",
                    "started_at": "2024-01-15 10:30:00",
                    "finished_at": "2024-01-15 10:30:02",
                    "message": "消息已进入工作流",
                },
                {
                    "id": "1-2",
                    "title": "识别用户意图",
                    "status": "completed",
                    "agent": "意图识别Agent",
                    "started_at": "2024-01-15 10:30:02",
                    "finished_at": "2024-01-15 10:30:12",
                    "message": "识别为产品功能咨询",
                },
                {
                    "id": "1-3",
                    "title": "生成回复内容",
                    "status": "completed",
                    "agent": "写作Agent",
                    "started_at": "2024-01-15 10:30:12",
                    "finished_at": "2024-01-15 10:30:45",
                    "message": "已完成邮件式回复生成",
                },
            ],
            "2": [
                {
                    "id": "2-1",
                    "title": "安全检测",
                    "status": "completed",
                    "agent": "安全检测Agent",
                    "started_at": "2024-01-15 10:32:00",
                    "finished_at": "2024-01-15 10:32:05",
                    "message": "输入安全检查通过",
                },
                {
                    "id": "2-2",
                    "title": "知识库检索",
                    "status": "running",
                    "agent": "搜索Agent",
                    "started_at": "2024-01-15 10:32:05",
                    "finished_at": None,
                    "message": "正在检索技术规格文档",
                },
            ],
        }

        self.users = [
            {
                "id": "1",
                "name": "张管理",
                "email": "zhang***@company.com",
                "role": "admin",
                "status": "active",
                "last_login": "2024-01-15 10:30",
                "total_interactions": 1250,
                "created_at": "2023-06-01",
            },
            {
                "id": "2",
                "name": "李运维",
                "email": "li***@company.com",
                "role": "operator",
                "status": "active",
                "last_login": "2024-01-15 09:15",
                "total_interactions": 856,
                "created_at": "2023-08-15",
            },
            {
                "id": "3",
                "name": "王查看",
                "email": "wang***@company.com",
                "role": "viewer",
                "status": "active",
                "last_login": "2024-01-14 18:20",
                "total_interactions": 234,
                "created_at": "2023-10-20",
            },
            {
                "id": "4",
                "name": "刘测试",
                "email": "liu***@company.com",
                "role": "operator",
                "status": "inactive",
                "last_login": "2024-01-10 14:30",
                "total_interactions": 567,
                "created_at": "2023-09-05",
            },
            {
                "id": "5",
                "name": "陈开发",
                "email": "chen***@company.com",
                "role": "admin",
                "status": "active",
                "last_login": "2024-01-15 08:00",
                "total_interactions": 2340,
                "created_at": "2023-05-10",
            },
            {
                "id": "6",
                "name": "赵客服",
                "email": "zhao***@company.com",
                "role": "operator",
                "status": "suspended",
                "last_login": "2024-01-05 11:45",
                "total_interactions": 89,
                "created_at": "2023-12-01",
            },
        ]

        self.user_profiles = {
            "1": {
                "id": "1",
                "name": "张管理",
                "email": "zhang***@company.com",
                "role": "admin",
                "status": "active",
                "last_login": "2024-01-15 10:30",
                "total_interactions": 1250,
                "created_at": "2023-06-01",
                "tags": ["核心管理层", "高频使用"],
                "notes": "负责审批与系统配置。",
                "preferred_language": "zh",
                "source_channels": ["dingtalk", "wecom"],
                "platform_accounts": [
                    {"platform": "dingtalk", "account_id": "ding-zhang-admin"},
                    {"platform": "telegram", "account_id": "tg_zhang_admin"},
                ],
            }
        }

        self.audit_logs = [
            {
                "id": "1",
                "timestamp": "2024-01-15 10:32:15",
                "action": "敏感词检测",
                "user": "system",
                "resource": "消息过滤",
                "status": "warning",
                "ip": "192.168.1.***",
                "details": "检测到敏感内容，已自动过滤",
            },
            {
                "id": "2",
                "timestamp": "2024-01-15 10:30:45",
                "action": "用户登录",
                "user": "zhang***",
                "resource": "认证系统",
                "status": "success",
                "ip": "10.0.0.***",
                "details": "管理员登录成功",
            },
            {
                "id": "3",
                "timestamp": "2024-01-15 10:28:30",
                "action": "权限变更",
                "user": "admin",
                "resource": "用户管理",
                "status": "success",
                "ip": "10.0.0.***",
                "details": "修改用户 li*** 的角色为运维员",
            },
            {
                "id": "4",
                "timestamp": "2024-01-15 10:25:10",
                "action": "异常请求",
                "user": "anonymous",
                "resource": "API 网关",
                "status": "error",
                "ip": "203.0.113.***",
                "details": "检测到异常请求模式，已阻止",
            },
            {
                "id": "5",
                "timestamp": "2024-01-15 10:20:00",
                "action": "工作流修改",
                "user": "chen***",
                "resource": "工作流编辑器",
                "status": "success",
                "ip": "10.0.0.***",
                "details": "更新客户服务工作流配置",
            },
            {
                "id": "6",
                "timestamp": "2024-01-15 10:15:30",
                "action": "Token 超限",
                "user": "system",
                "resource": "写作Agent",
                "status": "warning",
                "ip": "-",
                "details": "Agent Token 使用量达到 90%",
            },
            {
                "id": "7",
                "timestamp": "2024-01-15 10:10:00",
                "action": "登录失败",
                "user": "unknown",
                "resource": "认证系统",
                "status": "error",
                "ip": "198.51.100.***",
                "details": "连续 5 次登录失败，IP 已临时封禁",
            },
        ]

        self.security_rules = [
            {
                "id": "1",
                "name": "敏感词过滤",
                "description": "过滤包含敏感词汇的用户输入",
                "type": "filter",
                "enabled": True,
                "hit_count": 1250,
                "last_triggered": "2 分钟前",
            },
            {
                "id": "2",
                "name": "SQL 注入检测",
                "description": "检测并阻止 SQL 注入攻击",
                "type": "block",
                "enabled": True,
                "hit_count": 89,
                "last_triggered": "1 小时前",
            },
            {
                "id": "3",
                "name": "XSS 防护",
                "description": "过滤跨站脚本攻击代码",
                "type": "block",
                "enabled": True,
                "hit_count": 156,
                "last_triggered": "30 分钟前",
            },
            {
                "id": "4",
                "name": "频率限制",
                "description": "限制单用户请求频率",
                "type": "alert",
                "enabled": True,
                "hit_count": 432,
                "last_triggered": "5 分钟前",
            },
            {
                "id": "5",
                "name": "恶意内容检测",
                "description": "检测恶意或有害内容",
                "type": "filter",
                "enabled": True,
                "hit_count": 78,
                "last_triggered": "15 分钟前",
            },
            {
                "id": "6",
                "name": "IP 黑名单",
                "description": "阻止已知恶意 IP 访问",
                "type": "block",
                "enabled": True,
                "hit_count": 234,
                "last_triggered": "10 分钟前",
            },
            {
                "id": "7",
                "name": "数据脱敏",
                "description": "自动脱敏敏感个人信息",
                "type": "filter",
                "enabled": True,
                "hit_count": 5680,
                "last_triggered": "刚刚",
            },
        ]

        self.workflows = [
            {
                "id": "workflow-1",
                "name": "客户服务工作流",
                "description": "处理用户咨询并聚合结果",
                "version": "v2.1",
                "status": "active",
                "updated_at": "2026-04-01T17:00:00Z",
                "node_count": 8,
                "edge_count": 9,
                "trigger": {
                    "type": "message",
                    "keyword": "搜索, 写作, 帮助",
                    "cron": None,
                    "webhook_path": None,
                    "description": "默认消息入口，按关键词进入客户服务工作流",
                    "step_delay_seconds": 0.6,
                    "max_dispatch_retry": 6,
                    "dispatch_retry_backoff_seconds": 2.0,
                    "execution_timeout_seconds": 45.0,
                },
                "agent_bindings": ["2", "1", "3", "4", "6"],
                "nodes": [
                    {"id": "1", "type": "trigger", "label": "消息触发", "x": 50, "y": 200},
                    {"id": "2", "type": "agent", "label": "安全检测", "x": 280, "y": 120, "agent_id": "2"},
                    {"id": "3", "type": "agent", "label": "意图识别", "x": 280, "y": 280, "agent_id": "1"},
                    {"id": "4", "type": "condition", "label": "意图分支", "x": 520, "y": 200},
                    {"id": "5", "type": "agent", "label": "搜索 Agent", "x": 760, "y": 120, "agent_id": "3"},
                    {"id": "6", "type": "agent", "label": "写作 Agent", "x": 760, "y": 280, "agent_id": "4"},
                    {"id": "7", "type": "merge", "label": "结果合流", "x": 1000, "y": 200},
                    {"id": "8", "type": "output", "label": "发送结果", "x": 1240, "y": 200, "agent_id": "6"},
                ],
                "edges": [
                    {"id": "e1-2", "source": "1", "target": "2", "source_handle": None},
                    {"id": "e1-3", "source": "1", "target": "3", "source_handle": None},
                    {"id": "e2-4", "source": "2", "target": "4", "source_handle": None},
                    {"id": "e3-4", "source": "3", "target": "4", "source_handle": None},
                    {"id": "e4-5", "source": "4", "target": "5", "source_handle": "true"},
                    {"id": "e4-6", "source": "4", "target": "6", "source_handle": "false"},
                    {"id": "e5-7", "source": "5", "target": "7", "source_handle": None},
                    {"id": "e6-7", "source": "6", "target": "7", "source_handle": None},
                    {"id": "e7-8", "source": "7", "target": "8", "source_handle": None},
                ],
            }
        ]

        self.workflow_runs = []

    @staticmethod
    def now_string() -> str:
        return datetime.now(UTC).isoformat()

    def clone(self, value: object) -> object:
        return deepcopy(value)


store = InMemoryStore()
