from __future__ import annotations


BRAIN_EVENT_SPEC_VERSION = "brain_event.v1"
EVENT_VERSION_V1 = "v1"

MESSAGE_TYPE_COMMAND = "command"
MESSAGE_TYPE_EVENT = "event"
MESSAGE_TYPE_RESULT = "result"
MESSAGE_TYPE_SNAPSHOT = "snapshot"
MESSAGE_TYPE_AUDIT = "audit"
MESSAGE_TYPE_REALTIME = "realtime"

MESSAGE_TYPES = {
    MESSAGE_TYPE_COMMAND,
    MESSAGE_TYPE_EVENT,
    MESSAGE_TYPE_RESULT,
    MESSAGE_TYPE_SNAPSHOT,
    MESSAGE_TYPE_AUDIT,
    MESSAGE_TYPE_REALTIME,
}
